from __future__ import annotations

from contracts.factor_research import FactorResearchSpec, ValidationThreshold

_SPEC_DATA = [{'description': 'Daily close-to-open return.',
  'display_name': 'pv_close_to_open',
  'factor_id': 'simplepv_pv_close_to_open',
  'factor_name': 'pv_close_to_open',
  'formula': '(close - open) / open',
  'frequency': 'day',
  'library': 'SimplePV',
  'metadata': {'ambiguities_by_category': {'evaluation': [],
                                           'field_mapping': [],
                                           'formula': [],
                                           'other': []},
               'authors': ['Factor Lab Team'],
               'evaluation_method': 'daily rank IC and long-short quintile spread',
               'extraction_scope': 'selected_factors',
               'extraction_validation': {'status': 'implemented', 'warnings': []},
               'factor_ambiguities_by_category': {'evaluation': [],
                                                  'field_mapping': [],
                                                  'formula': [],
                                                  'other': []},
               'implementation_stage': 'spec',
               'paper_id': 'simple_price_volume_demo',
               'portfolio_construction_rules': 'long top quintile, short bottom quintile',
               'proof_status_ceiling': 'paper_evaluation_match',
               'selected_truth_source_ids': [],
               'selected_truth_sources': [{'description': 'Table 3 reports rank IC and IR for the '
                                                          'factor.',
                                           'evaluation_method': 'daily rank IC and long-short '
                                                                'quintile spread',
                                           'frequency': 'day',
                                           'metrics': {'rank_ic_ir': 0.31, 'rank_ic_mean': 0.042},
                                           'notes': [],
                                           'sample_period': '2020-01-01 to 2020-12-31',
                                           'source_location': 'Table 3',
                                           'truth_id': 'pv_close_to_open_table_3_evaluation',
                                           'truth_type': 'evaluation_results',
                                           'universe': 'liquid common stocks'}],
               'source': 'Factor Lab fixture',
               'status': 'planned',
               'truth_match_required': True,
               'truth_selection_rule': '',
               'truth_source_summary': {'available_truth_count': 1,
                                        'available_truth_ids': ['pv_close_to_open_table_3_evaluation'],
                                        'available_truth_types': ['evaluation_results'],
                                        'has_evaluation_truth': True,
                                        'selected_truth_ids': ['pv_close_to_open_table_3_evaluation'],
                                        'selected_truth_types': ['evaluation_results']},
               'truth_sources': [{'description': 'Table 3 reports rank IC and IR for the factor.',
                                  'evaluation_method': 'daily rank IC and long-short quintile '
                                                       'spread',
                                  'frequency': 'day',
                                  'metrics': {'rank_ic_ir': 0.31, 'rank_ic_mean': 0.042},
                                  'notes': [],
                                  'sample_period': '2020-01-01 to 2020-12-31',
                                  'source_location': 'Table 3',
                                  'truth_id': 'pv_close_to_open_table_3_evaluation',
                                  'truth_type': 'evaluation_results',
                                  'universe': 'liquid common stocks'}],
               'year': 2026},
  'neutralization': [],
  'notes': ['Paper evaluation-result truth sources extracted for matching.'],
  'parameters': {},
  'preprocessing': ['adjust prices', 'sort by date and code'],
  'required_fields': ['open', 'close'],
  'sample_scope': '2020-01-01 to 2020-12-31; universe: liquid common stocks',
  'source_document': 'Simple Price-Volume Signals (Factor Lab fixture, 2026)',
  'tags': ['simplepv', 'paper-reproduction', 'price-volume', 'paper-evaluation-truth'],
  'validation_targets': [{'description': 'Implementation formula must match the extracted paper '
                                         'formula.',
                          'metric': 'formula_match_ratio',
                          'operator': '>=',
                          'value': 1.0},
                         {'description': 'Required input fields must match the extracted data '
                                         'requirements.',
                          'metric': 'field_mapping_match_ratio',
                          'operator': '>=',
                          'value': 1.0},
                         {'description': 'Computed evaluation metrics must match evaluation '
                                         'results reported in the paper.',
                          'metric': 'paper_evaluation_metric_match_ratio',
                          'operator': '>=',
                          'value': 1.0}],
  'version': 'v2026.06'},
 {'description': 'Volume relative to its 5-day moving average.',
  'display_name': 'pv_volume_momentum_5d',
  'factor_id': 'simplepv_pv_volume_momentum_5d',
  'factor_name': 'pv_volume_momentum_5d',
  'formula': 'volume / mean(volume, 5) - 1',
  'frequency': 'day',
  'library': 'SimplePV',
  'metadata': {'ambiguities_by_category': {'evaluation': [],
                                           'field_mapping': [],
                                           'formula': [],
                                           'other': []},
               'authors': ['Factor Lab Team'],
               'evaluation_method': 'daily rank IC and long-short quintile spread',
               'extraction_scope': 'selected_factors',
               'extraction_validation': {'status': 'implemented', 'warnings': []},
               'factor_ambiguities_by_category': {'evaluation': [],
                                                  'field_mapping': [],
                                                  'formula': [],
                                                  'other': []},
               'implementation_stage': 'spec',
               'paper_id': 'simple_price_volume_demo',
               'portfolio_construction_rules': '',
               'proof_status_ceiling': 'paper_evaluation_match',
               'selected_truth_source_ids': [],
               'selected_truth_sources': [{'description': 'Table 3 reports evaluation metrics.',
                                           'evaluation_method': 'daily rank IC and long-short '
                                                                'quintile spread',
                                           'frequency': 'day',
                                           'metrics': {'rank_ic_ir': 0.12, 'rank_ic_mean': 0.018},
                                           'notes': [],
                                           'sample_period': '2020-01-01 to 2020-12-31',
                                           'source_location': 'Table 3',
                                           'truth_id': 'pv_volume_table_3_evaluation',
                                           'truth_type': 'evaluation_results',
                                           'universe': 'liquid common stocks'}],
               'source': 'Factor Lab fixture',
               'status': 'planned',
               'truth_match_required': True,
               'truth_selection_rule': '',
               'truth_source_summary': {'available_truth_count': 1,
                                        'available_truth_ids': ['pv_volume_table_3_evaluation'],
                                        'available_truth_types': ['evaluation_results'],
                                        'has_evaluation_truth': True,
                                        'selected_truth_ids': ['pv_volume_table_3_evaluation'],
                                        'selected_truth_types': ['evaluation_results']},
               'truth_sources': [{'description': 'Table 3 reports evaluation metrics.',
                                  'evaluation_method': 'daily rank IC and long-short quintile '
                                                       'spread',
                                  'frequency': 'day',
                                  'metrics': {'rank_ic_ir': 0.12, 'rank_ic_mean': 0.018},
                                  'notes': [],
                                  'sample_period': '2020-01-01 to 2020-12-31',
                                  'source_location': 'Table 3',
                                  'truth_id': 'pv_volume_table_3_evaluation',
                                  'truth_type': 'evaluation_results',
                                  'universe': 'liquid common stocks'}],
               'year': 2026},
  'neutralization': [],
  'notes': ['Paper evaluation-result truth sources extracted for matching.'],
  'parameters': {'window': 5},
  'preprocessing': ['sort by date and code'],
  'required_fields': ['volume'],
  'sample_scope': '2020-01-01 to 2020-12-31; universe: liquid common stocks',
  'source_document': 'Simple Price-Volume Signals (Factor Lab fixture, 2026)',
  'tags': ['simplepv', 'paper-reproduction', 'price-volume', 'paper-evaluation-truth'],
  'validation_targets': [{'description': 'Implementation formula must match the extracted paper '
                                         'formula.',
                          'metric': 'formula_match_ratio',
                          'operator': '>=',
                          'value': 1.0},
                         {'description': 'Required input fields must match the extracted data '
                                         'requirements.',
                          'metric': 'field_mapping_match_ratio',
                          'operator': '>=',
                          'value': 1.0},
                         {'description': 'Computed evaluation metrics must match evaluation '
                                         'results reported in the paper.',
                          'metric': 'paper_evaluation_metric_match_ratio',
                          'operator': '>=',
                          'value': 1.0}],
  'version': 'v2026.06'}]


def simplepv_specs() -> list[FactorResearchSpec]:
    specs: list[FactorResearchSpec] = []
    for item in _SPEC_DATA:
        payload = dict(item)
        payload["validation_targets"] = [ValidationThreshold(**threshold) for threshold in payload["validation_targets"]]
        specs.append(FactorResearchSpec(**payload))
    return specs
