from __future__ import annotations

from research_core.factor_lab.paper_reproduction.agent_harness import (
    PaperReproductionAgentHarnessBundle,
    PaperReproductionAgentHarnessRequest,
    default_skill_path,
    prepare_agent_harness_bundle,
)
from research_core.factor_lab.paper_reproduction.data_validation import (
    DataProfile,
    DataFrameValidationRequest,
    DataFrameValidationResult,
    EvaluationCaseSupportAssessment,
    EvaluationRequirementResult,
    assess_evaluation_case_support,
    build_data_profile,
    structured_deviation,
    validate_input_frame,
)
from research_core.factor_lab.paper_reproduction.extraction import (
    ExtractedFactor,
    ExtractedTruthSource,
    ExtractionValidationResult,
    PaperExtraction,
    export_paper_extraction,
    load_paper_extraction,
    selected_truth_sources,
    summarize_factor_truth_sources,
    validate_paper_extraction,
)
from research_core.factor_lab.paper_reproduction.evaluators import (
    GENERIC_EVALUATOR_CAPABILITIES,
    apply_transform_spec,
    compute_cross_sectional_regression,
    compute_ic_analysis,
    evaluator_capabilities_for_case,
    evaluate_paper_case,
    get_generic_evaluator_capabilities,
)
from research_core.factor_lab.paper_reproduction.implementation import (
    FactorImplementationPlan,
    FamilyImplementationManifest,
    build_implementation_manifest,
    export_implementation_manifest,
    write_factor_family_scaffold,
)
from research_core.factor_lab.paper_reproduction.normalization import (
    normalize_extraction_to_specs,
    write_specs_module,
)
from research_core.factor_lab.paper_reproduction.paper_evaluation import (
    PaperEvaluationPlan,
    PaperFactorEvaluationPlan,
    build_paper_evaluation_plan,
)
from research_core.factor_lab.paper_reproduction.pipeline import (
    PaperReproductionPipelineState,
    PaperReproductionStage,
    PaperReproductionStageState,
    StageExecutionDecision,
    export_pipeline_state,
    load_pipeline_state,
    merge_pipeline_stage_update,
)
from research_core.factor_lab.paper_reproduction.quant_api import (
    QuantApiConfig,
    normalize_quant_daily_kline_frame,
)
from research_core.factor_lab.paper_reproduction.recommended_data import (
    PAPER_PRICE_ADJUSTMENT_VIEWS,
    RecommendedDataConfig,
    add_next_suspension_flag,
    apply_a_share_recommended_filters,
    build_recommended_price_view,
    load_recommended_daily_panel,
    load_recommended_data_manifest,
    load_recommended_paper_panels,
    normalize_recommended_daily_kline_frame,
    normalize_recommended_industry_frame,
    normalize_recommended_market_cap_frame,
    normalize_recommended_symbol,
    recommended_data_available,
)
from research_core.factor_lab.paper_reproduction.reporting import (
    build_paper_reproduction_report,
    export_paper_reproduction_report,
    render_paper_reproduction_report_markdown,
)
from research_core.factor_lab.paper_reproduction.truth_matching import (
    PaperTruthMatchResult,
    compare_evaluation_metrics_to_paper_truth,
)

__all__ = [
    "DataFrameValidationRequest",
    "DataFrameValidationResult",
    "DataProfile",
    "EvaluationCaseSupportAssessment",
    "EvaluationRequirementResult",
    "ExtractedFactor",
    "ExtractedTruthSource",
    "ExtractionValidationResult",
    "FactorImplementationPlan",
    "FamilyImplementationManifest",
    "PaperExtraction",
    "PaperEvaluationPlan",
    "PaperFactorEvaluationPlan",
    "PaperReproductionAgentHarnessBundle",
    "PaperReproductionAgentHarnessRequest",
    "PaperReproductionPipelineState",
    "PaperReproductionStage",
    "PaperReproductionStageState",
    "PaperTruthMatchResult",
    "PAPER_PRICE_ADJUSTMENT_VIEWS",
    "QuantApiConfig",
    "RecommendedDataConfig",
    "StageExecutionDecision",
    "GENERIC_EVALUATOR_CAPABILITIES",
    "add_next_suspension_flag",
    "apply_transform_spec",
    "apply_a_share_recommended_filters",
    "assess_evaluation_case_support",
    "build_data_profile",
    "build_recommended_price_view",
    "build_implementation_manifest",
    "build_paper_evaluation_plan",
    "build_paper_reproduction_report",
    "compare_evaluation_metrics_to_paper_truth",
    "compute_cross_sectional_regression",
    "compute_ic_analysis",
    "default_skill_path",
    "evaluate_paper_case",
    "evaluator_capabilities_for_case",
    "export_implementation_manifest",
    "export_pipeline_state",
    "export_paper_extraction",
    "export_paper_reproduction_report",
    "load_paper_extraction",
    "load_pipeline_state",
    "load_recommended_daily_panel",
    "load_recommended_data_manifest",
    "load_recommended_paper_panels",
    "normalize_extraction_to_specs",
    "normalize_quant_daily_kline_frame",
    "normalize_recommended_daily_kline_frame",
    "normalize_recommended_industry_frame",
    "normalize_recommended_market_cap_frame",
    "normalize_recommended_symbol",
    "prepare_agent_harness_bundle",
    "recommended_data_available",
    "render_paper_reproduction_report_markdown",
    "selected_truth_sources",
    "structured_deviation",
    "summarize_factor_truth_sources",
    "get_generic_evaluator_capabilities",
    "merge_pipeline_stage_update",
    "validate_paper_extraction",
    "validate_input_frame",
    "write_factor_family_scaffold",
    "write_specs_module",
]
